-- ============================================================
-- Anchorix v0.1 — initial schema (proposal)
--
-- Append-only migrations (CLAUDE.md §5.9). Do not edit this file
-- after it has been merged. Add a new numbered migration instead.
--
-- Conventions:
--   - All ids are TEXT (opaque hex/UUID strings; see internal/ids).
--   - All timestamps are TIMESTAMPTZ stored in UTC.
--   - All foreign keys are explicit and indexed.
--   - JSON blobs use JSONB.
--   - Audit-relevant columns are immutable in application logic.
-- ============================================================

BEGIN;

-- ----------------------------------------
-- Organizations (single row in v0.1; multi-tenant deferred).
-- ----------------------------------------
CREATE TABLE organizations (
    id              TEXT PRIMARY KEY,
    name            TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------------------------
-- Users (operators).
-- ----------------------------------------
CREATE TABLE users (
    id                  TEXT        PRIMARY KEY,
    organization_id     TEXT        NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    email               TEXT        NOT NULL,
    display_name        TEXT        NOT NULL,
    role                TEXT        NOT NULL CHECK (role IN ('operator', 'admin')),
    password_hash       BYTEA       NOT NULL, -- bcrypt; never logged
    disabled            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at       TIMESTAMPTZ,
    UNIQUE (organization_id, email)
);
CREATE INDEX users_org_idx ON users(organization_id);

-- ----------------------------------------
-- Sessions (server-side; cookie carries a signed session id).
-- ----------------------------------------
CREATE TABLE sessions (
    id              TEXT        PRIMARY KEY,
    user_id         TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL,
    revoked_at      TIMESTAMPTZ,
    user_agent      TEXT,
    remote_ip       INET
);
CREATE INDEX sessions_user_idx ON sessions(user_id);
CREATE INDEX sessions_expires_idx ON sessions(expires_at);

-- ----------------------------------------
-- Agents (registered Windows hosts).
-- ----------------------------------------
CREATE TABLE agents (
    id                          TEXT        PRIMARY KEY,
    organization_id             TEXT        NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    hostname                    TEXT        NOT NULL,
    version                     TEXT        NOT NULL DEFAULT '',
    status                      TEXT        NOT NULL CHECK (status IN ('pending_enrollment','active','disabled','revoked')),
    public_key_fingerprint      TEXT        NOT NULL,
    enrolled_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (organization_id, public_key_fingerprint)
);
CREATE INDEX agents_org_idx ON agents(organization_id);
CREATE INDEX agents_status_idx ON agents(status);

-- ----------------------------------------
-- Single-use enrollment tokens.
-- We store ONLY the SHA-256 of the token, never the token itself.
-- ----------------------------------------
CREATE TABLE agent_enrollment_tokens (
    id              TEXT        PRIMARY KEY,
    organization_id TEXT        NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    token_hash      BYTEA       NOT NULL UNIQUE, -- sha256(token)
    issued_by       TEXT        NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    issued_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL,
    consumed_at     TIMESTAMPTZ
);
CREATE INDEX enroll_tokens_org_idx ON agent_enrollment_tokens(organization_id);
CREATE INDEX enroll_tokens_expires_idx ON agent_enrollment_tokens(expires_at);

-- ----------------------------------------
-- Certificates (deduplicated by fingerprint per organization).
-- Public-cert metadata only. NO private key columns. EVER.
-- ----------------------------------------
CREATE TABLE certificates (
    id                      TEXT        PRIMARY KEY,
    organization_id         TEXT        NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    fingerprint_sha256      TEXT        NOT NULL,
    subject                 TEXT        NOT NULL,
    issuer                  TEXT        NOT NULL,
    serial_number_hex       TEXT        NOT NULL,
    signature_algorithm     TEXT        NOT NULL,
    public_key_algorithm    TEXT        NOT NULL,
    public_key_bits         INTEGER     NOT NULL,
    not_before              TIMESTAMPTZ NOT NULL,
    not_after               TIMESTAMPTZ NOT NULL,
    sans                    JSONB       NOT NULL DEFAULT '[]'::jsonb,
    key_usages              JSONB       NOT NULL DEFAULT '[]'::jsonb,
    ext_key_usages          JSONB       NOT NULL DEFAULT '[]'::jsonb,
    is_self_signed          BOOLEAN     NOT NULL DEFAULT FALSE,
    is_ca                   BOOLEAN     NOT NULL DEFAULT FALSE,
    pem                     TEXT        NOT NULL, -- PUBLIC certificate PEM only
    first_seen_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (organization_id, fingerprint_sha256)
);
CREATE INDEX certificates_org_idx     ON certificates(organization_id);
CREATE INDEX certificates_not_after_idx ON certificates(not_after);
CREATE INDEX certificates_subject_idx ON certificates(subject);

-- ----------------------------------------
-- Observations (a sighting of a certificate at host+store via an agent).
-- ----------------------------------------
CREATE TABLE certificate_observations (
    id              TEXT        PRIMARY KEY,
    certificate_id  TEXT        NOT NULL REFERENCES certificates(id) ON DELETE CASCADE,
    agent_id        TEXT        NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    hostname        TEXT        NOT NULL,
    store_location  TEXT        NOT NULL,
    friendly_name   TEXT,
    observed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (certificate_id, agent_id, store_location)
);
CREATE INDEX cert_obs_cert_idx  ON certificate_observations(certificate_id);
CREATE INDEX cert_obs_agent_idx ON certificate_observations(agent_id);

-- ----------------------------------------
-- Findings (risks attached to certificates).
-- ----------------------------------------
CREATE TABLE findings (
    id              TEXT        PRIMARY KEY,
    organization_id TEXT        NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    certificate_id  TEXT        NOT NULL REFERENCES certificates(id) ON DELETE CASCADE,
    rule_id         TEXT        NOT NULL,
    severity        TEXT        NOT NULL CHECK (severity IN ('info','low','medium','high','critical')),
    status          TEXT        NOT NULL CHECK (status IN ('open','acknowledged','suppressed','resolved')),
    title           TEXT        NOT NULL,
    evidence        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    opened_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (organization_id, certificate_id, rule_id)
);
CREATE INDEX findings_org_idx          ON findings(organization_id);
CREATE INDEX findings_status_sev_idx   ON findings(status, severity);
CREATE INDEX findings_certificate_idx  ON findings(certificate_id);

-- ----------------------------------------
-- Providers (registered PKI / secret / transport providers).
-- v0.1 stores configuration only; no live integration calls.
-- ----------------------------------------
CREATE TABLE providers (
    id              TEXT        PRIMARY KEY,
    organization_id TEXT        NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    domain          TEXT        NOT NULL CHECK (domain IN ('pki','secrets','transport')),
    kind            TEXT        NOT NULL,
    display_name    TEXT        NOT NULL,
    config          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    enabled         BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX providers_org_idx ON providers(organization_id);

-- ----------------------------------------
-- Audit events (insert-only).
-- A trigger enforces the no-update / no-delete invariant.
-- ----------------------------------------
CREATE TABLE audit_events (
    id              TEXT        PRIMARY KEY,
    organization_id TEXT        NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor           TEXT        NOT NULL,
    actor_type      TEXT        NOT NULL CHECK (actor_type IN ('user','agent','system')),
    action          TEXT        NOT NULL,
    target_type     TEXT        NOT NULL,
    target_id       TEXT        NOT NULL,
    request_id      TEXT,
    metadata        JSONB       NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX audit_events_org_time_idx ON audit_events(organization_id, occurred_at DESC);
CREATE INDEX audit_events_target_idx   ON audit_events(target_type, target_id);

CREATE OR REPLACE FUNCTION audit_events_immutable()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'audit_events is insert-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_events_no_update
BEFORE UPDATE ON audit_events
FOR EACH ROW EXECUTE FUNCTION audit_events_immutable();

CREATE TRIGGER audit_events_no_delete
BEFORE DELETE ON audit_events
FOR EACH ROW EXECUTE FUNCTION audit_events_immutable();

-- ----------------------------------------
-- Schema migration tracking.
-- ----------------------------------------
CREATE TABLE schema_migrations (
    version     INTEGER      PRIMARY KEY,
    applied_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

INSERT INTO schema_migrations(version) VALUES (1);

COMMIT;
